services:
  postgres_db:
    image: postgres:16
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    # ports:
    #   - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
  server:
    depends_on:
      - postgres_db
    build: ./server
    environment:
      DB_DSN: "host=postgres_db user=myuser password=mypassword dbname=mydatabase port=5432 sslmode=disable TimeZone=Asia/Shanghai"
      API_LISTEN_ADDR: "0.0.0.0:5433"
    # ports:
    #   - "127.0.0.1:5433:5433"
    restart: always
  web:
    depends_on:
      - server
    build: ./web
    environment:
      SERVER_ADDR: "http://server:5433"
      PORT: 3000
      HOSTNAME: "0.0.0.0"
    ports:
      - "3000:3000"
    restart: always

volumes:
  postgres_data:
