services:
  ai_backend:
    build: ./ai
    volumes:
      - ./ai:/app
      - /etc/localtime:/etc/localtime:ro
      - ./ai/cache:/root/.cache/
    env_file:
      - ./ai/.env
    environment:
      PORT: 8000
    working_dir: /app
    restart: always
    entrypoint: python3 main.py
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/api/health || exit 1"]

  postgres_db:
    image: postgres:16
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: always

  api_backend:
    depends_on:
      - postgres_db
    build: ./server
    environment:
      API_LISTEN_ADDR: "0.0.0.0:5433"
      API_DATA_SOURCE_NAME: 'host=postgres_db user=myuser password=mypassword dbname=mydatabase port=5432 sslmode=disable TimeZone=Asia/Shanghai'
      API_JWT_SECRET_KEY: 123
      API_AI_SERVER_ADDR: "http://ai_backend:8000"
    restart: always

  web:
    build: ./web
    restart: always

  nginx:
    image: nginx:1.27
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api_backend
      - web
    restart: always
    ports:
      - 8911:80

# volumes:
#   postgres_data:
