services:
  ai-backend:
    build: .
    volumes:
      - ${PWD}:/app
      - /etc/localtime:/etc/localtime:ro
    working_dir: /app
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    restart: always
    entrypoint: python3 main.py
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${PORT}/api/health || exit 1"]
    dns:
      - 223.5.5.5
      - 119.29.29.29
      - 1.2.4.8
      - 114.114.114.114
