port: 8000
workers: 1

openai:
  api_key: ""  # Change this with your own
  model: "gpt-3.5-turbo"
  base_url: "https://api.openai.com/v1"

vector_db:
  model_name_or_path: "BAAI/bge-m3"
  batch_size: 1
  device: "cpu"
  path: "chroma_data"

ranker:
  model_name_or_path: "BAAI/bge-reranker-v2-m3"
  batch_size: 1
  device: "cpu"
